### ISSUE TITLE
初始化后，运行 npm run serve:web 报错

### ISSUE THREAD

**Issue by QiuShuiBai** [mpx-ecology/mpx-cli#42]
初始化跨端项目后，运行 npm run serve:web 报错。

报错:
`Property 'getApp' does not exist on type 'typeof globalThis'.`
`Property 'getCurrentPages' does not exist on type 'typeof globalThis'`

版本:
`mpx -V   @mpx/cli 3.2.0`
`node -v   v16.13.0 `

![image](https://user-images.githubusercontent.com/33334963/175849695-643578cd-280d-49af-8809-df9af0f028dd.png)
![image](https://user-images.githubusercontent.com/33334963/175849861-04dcc714-5577-4eda-b9ff-bc22e6d31039.png)

**Comment by mater1996** [comment]
fixed #49
