### ISSUE TITLE
bug: 环境变量 MPX_CURRENT_TARGET_ENV 不存在

### ISSUE THREAD

**Issue by lp0124** [mpx-ecology/mpx-cli#94]
使用新版 cli@2.1.15 版本打印 console.log(process.env) 未返回 MPX_CURRENT_TARGET_ENV

<img width="355" alt="image" src="https://github.com/user-attachments/assets/a8a4a131-e4f0-47a3-aadf-053dac4aad51">

**Comment by lp0124** [comment]
是直接在 vue.config.js 里打印的没有

**Comment by mater1996** [comment]
这个只会在单独指定target env的时候才会出现
例如 mpx-cli-service build --targets=wx:development
正常使用直接用NODE_ENV就ok
